<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>false</UseWindowsForms>
    <ApplicationIcon>Images\mainlogo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Infrastructure\**" />
    <EmbeddedResource Remove="Infrastructure\**" />
    <None Remove="Infrastructure\**" />
    <Page Remove="Infrastructure\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\copy.png" />
    <None Remove="Images\smartemr_booking.png" />
    <None Remove="Images\smartemr_check.png" />
    <None Remove="Images\smartemr_clear.png" />
    <None Remove="Images\smartemr_cross.png" />
    <None Remove="Images\smartemr_delete.png" />
    <None Remove="Images\smartemr_delete_v2.png" />
    <None Remove="Images\smartemr_desk_register.png" />
    <None Remove="Images\smartemr_edit_patient.png" />
    <None Remove="Images\smartemr_find_address.png" />
    <None Remove="Images\smartemr_info.png" />
    <None Remove="Images\smartemr_menu_calendar.png" />
    <None Remove="Images\smartemr_menu_crm.png" />
    <None Remove="Images\smartemr_menu_desk.png" />
    <None Remove="Images\smartemr_menu_exam.png" />
    <None Remove="Images\smartemr_menu_payment.png" />
    <None Remove="Images\smartemr_menu_settings.png" />
    <None Remove="Images\smartemr_patient_default_image.png" />
    <None Remove="Images\smartemr_register.png" />
    <None Remove="Images\smartemr_save.png" />
    <None Remove="Images\Svg\smartemr-error.svg" />
    <None Remove="Images\Svg\smartemr_menu_calendar.svg" />
    <None Remove="Images\Svg\smartemr_menu_crm.svg" />
    <None Remove="Images\Svg\smartemr_menu_desk.svg" />
    <None Remove="Images\Svg\smartemr_menu_examination.svg" />
    <None Remove="Images\Svg\smartemr_menu_payment.svg" />
    <None Remove="Images\Svg\smartemr_menu_settings.svg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	<PackageReference Include="DevExpress.Mvvm" Version="25.2.6" />
	<PackageReference Include="DevExpress.Win.Design" Version="25.2.6" />
	<PackageReference Include="DevExpress.Win.Navigation" Version="25.2.6" />
	<PackageReference Include="DevExpress.Wpf.Controls" Version="25.2.6" />
	<PackageReference Include="DevExpress.Wpf.Core" Version="25.2.6" />
	<PackageReference Include="DevExpress.Wpf.Docking" Version="25.2.6" />
	<PackageReference Include="DevExpress.Wpf.LayoutControl" Version="25.2.6" />
    <PackageReference Include="HandyControl" Version="3.6.0-rc3" />
    <PackageReference Include="MahApps.Metro" Version="3.0.0-rc0529" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes.MahApps" Version="5.3.1" />
    <PackageReference Include="SharpVectors" Version="1.8.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartEMR.Domain\SmartEMR.Domain.csproj" />
    <ProjectReference Include="..\SmartEMR.Infrastructure\SmartEMR.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\Svg\smartemr-error.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\smartemr_clear.png" />
    <Resource Include="Images\smartemr_cross.png" />
    <Resource Include="Images\smartemr_delete_v2.png" />
    <Resource Include="Images\smartemr_find_address.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\copy.png" />
    <Resource Include="Images\smartemr_booking.png" />
    <Resource Include="Images\smartemr_check.png" />
    <Resource Include="Images\smartemr_delete.png" />
    <Resource Include="Images\smartemr_desk_register.png" />
    <Resource Include="Images\smartemr_edit_patient.png" />
    <Resource Include="Images\smartemr_patient_default_image.png" />
    <Resource Include="Images\smartemr_register.png" />
    <Resource Include="Images\smartemr_save.png" />
    <Resource Include="Images\smartemr_warning.png" />
    <Resource Include="Images\smartemr_info.png" />
    <Resource Include="Images\smartemr_menu_crm.png" />
    <Resource Include="Images\smartemr_menu_payment.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\smartemr_menu_calendar.png" />
    <Resource Include="Images\smartemr_menu_desk.png" />
    <Resource Include="Images\smartemr_menu_exam.png" />
    <Resource Include="Images\smartemr_menu_settings.png" />
    <Resource Include="Images\smartemr_error.png" />
    <Resource Include="Images\Svg\smartemr_menu_calendar.svg" />
    <Resource Include="Images\Svg\smartemr_menu_crm.svg" />
    <Resource Include="Images\Svg\smartemr_menu_desk.svg" />
    <Resource Include="Images\Svg\smartemr_menu_examination.svg" />
    <Resource Include="Images\Svg\smartemr_menu_payment.svg" />
    <Resource Include="Images\Svg\smartemr_menu_settings.svg" />
  </ItemGroup>

</Project>
