<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\mainlogo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartEMR.Domain\SmartEMR.Domain.csproj" />
    <ProjectReference Include="..\SmartEMR.Infrastructure\SmartEMR.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\Svg\" />
    <Folder Include="Infrastructure\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\mainlogo.png" />
  </ItemGroup>

</Project>
